language: ruby
rvm:
- 2.2

before_script:
 - chmod +x ./script/cibuild

# Assume bundler is being used, install step will run `bundle install`.
script: ./script/cibuild

# branch whitelist
branches:
  only:
  - master
  #- gh-pages     # test the gh-pages branch
  #- /pages-(.*)/ # test every branch which starts with "pages-"