language: ruby
cache: bundler
install:
- bundle install
script:
- "./script/cibuild"
branches:
  only:
  - master
env:
  global:
    secure: IWi4OTatkKbzaNCv3Q75GhuucKu0u8RGy/cf40yaTLn98Op9FrufGpdk3ICCR6mKnWq77Z2qu3t6xkpdg9+in0qitrYZuG/JOSzuYpm64Bxtr9hV3ao1FYR0a/mSAe3BnS3mswxcet5PCkuPfLCqtkqWi6Jl/2LyOn/ylSNjfQg=
