# Build settings
encoding: utf-8
# pygments does not work yet from my Windows machine
#highlighter: pygments
highlighter: rouge
# https://help.github.com/articles/emoji-on-github-pages/
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
# markdown rendering
markdown: kramdown
# http://jekyllrb.com/docs/configuration/#kramdown
kramdown:
  input: GFM
# SASS
sass:
  style: :compressed
# Site settings
locale: "en_US"
title: "Captivating Online Matters"
email: "hello@johanbove.info"
description: "Johan is a front end web developer passionate about media and technology."
#baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://blog.johanbove.info" # the base hostname & protocol for your site
twitter_username: "johanbove"
github_username: "johanbove"
skype_username: "johanbove"
linkedin_username: "johanbove"
googleplus_username: "+JohanBové"
#evernote_username: "joe-1"
keybase_username: "johanbove"
birthyear: 1980
themeColor: "#0E0412"
exclude: [vendor]
excerpt_separator: <!--more-->
