# Build settings
encoding: utf-8
markdown: kramdown
highlighter: pygments

# Site settings
title: "Reflections Of My Digital Self"
email: "hello@johanbove.info"
description: "Johan is a front end web developer passionate about media and technology."
#baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://johanbove.info" # the base hostname & protocol for your site
twitter_username: "johanbove"
github_username:  "johanbove"
skype_username:   "johanbove"
linkedin_username:   "johanbove"
googleplus_username:   "+JohanBové"
evernote_username:      "joe-1"

